## Estudando Data Science

### Numpy

In [1]:
# Importando bibioteca
import numpy as np

In [5]:
lista = [1,1,1,1,1,1]
array = np.array(lista)

print(lista,array)

[1, 1, 1, 1, 1, 1] [1 1 1 1 1 1]


In [6]:
#Criar uma array de zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
#Matrizes
# (Linhas,Colunas)
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# Operações matemáticas
lista_notas = [5,3,7]
notas= np.array(lista_notas)
print('Desvio padrão', notas.std())
print('Média',notas.mean())
print('Posição menor', notas.argmin())

Desvio padrão 1.632993161855452
Média 5.0
Posição menor 1


In [29]:
notas = np.zeros(2)
for i in range(len(notas)):
    notas[i] = 2
    
notas

array([2., 2.])

### Máscara Booleana